/*Copyright [2014] [Harshvardhan J Pandit]

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License. */

package msc.prototype.context;

import android.os.Parcelable;

/**
 * Context class
 * @author harsh
 * @version 1.0
 */
public abstract class ContextData implements Parcelable {
    private long _id;

    /**
     * get the id for the context object
     * @param token System token
     * @return long id
     */
    public final long get_id(SystemToken token) {
        return _id;
    }

    /**
     * Can only be accessed using SystemToken which can be generated by the system
     * @param token system token
     * @param _id the id to set
     * @see SystemToken
     */
    public final void set_id(SystemToken token, long _id) {
        this._id = _id;
    }

    /**
     * short description of context object
     * will contain only vital fields and information
     * @return String containing short description
     */
    public abstract String shortDescribe();

    /**
     * longer description of context object
     * will contain all the fields and more information
     * @return String containing long description
     */
    public abstract String longDescribe();

    /**
     * checks the fields and returns if object is valid
     * @return true if all fields are valid, false otherwise
     */
    public abstract boolean checkFields();
}
